### PR TITLE
Fix definitionId filter support

### PR DESCRIPTION
**Pull request by matteopessina**
When definitionName is populated with the pipeline definition id, then it filter the releases by pipeline id.

### CODE REVIEW

**Comment by matteopessina** [comment]
It needs smoke test before being ready.

**Comment by matteopessina** [comment]
Hi @dmitryserbin, I created unit tests for changes but I cannot easily set up an environment for smoke test. 
In case you already have one, could you please make a smoke test?

**Comment by dmitryserbin** [comment]
> Hi @dmitryserbin, I created unit tests for changes but I cannot easily set up an environment for smoke test.
> In case you already have one, could you please make a smoke test?

Thanks for your contribution. I will have a look and run smoke tests shortly.

**Comment by dmitryserbin** [comment]
Pls fix [linting issues](https://www.codefactor.io/repository/github/dmitryserbin/azdev-release-orchestrator/pull/94) when you have a moment?

**Comment by matteopessina** [comment]
> Pls fix [linting issues](https://www.codefactor.io/repository/github/dmitryserbin/azdev-release-orchestrator/pull/94) when you have a moment?

Done.

**Comment by matteopessina** [comment]
Hi @dmitryserbin, is there something else that should be done on this PR? Can I help?

**Comment by dmitryserbin** [comment]
> Hi @dmitryserbin, is there something else that should be done on this PR? Can I help?

sorry got distracted with work. will test and release asap.

**Review by dmitryserbin — APPROVED** [review]

**Comment by dmitryserbin** [comment]
should be good to go, merge it when you're ready. i'll release it shortly after.

**Comment by matteopessina** [comment]
> should be good to go, merge it when you're ready. i'll release it shortly after.

Hi @dmitryserbin, I cannot merge. Could you do that for me?

image

**Comment by dmitryserbin** [comment]
> Hi @dmitryserbin, I cannot merge. Could you do that for me?

all good now

**Comment by dmitryserbin** [comment]
I'll tag you here when it's released @matteopessina. Thanks a lot for your contribution!

**Comment by matteopessina** [comment]
> I'll tag you here when it's released @matteopessina. Thanks a lot for your contribution!

You are welcome! Thank u for the task

**Comment by dmitryserbin** [comment]
Released under v3.1.1888

**Pull request merged**
