### PR TITLE
Fix buildNumber parameter name

### PR DESCRIPTION
**Pull request by Kacpermm**
Address invalid `buildNumber ` task parameter name #91

### CODE REVIEW

**Review by dmitryserbin — DISMISSED** [review]

**Comment by dmitryserbin** [comment]
Thanks for your contribution! I will get it merged and release asap.

**Review by dmitryserbin — APPROVED** [review]

**Comment by Kacpermm** [comment]
Thanks @dmitryserbin :D I wanted to help a little bit because I'm using this extension.

**Comment by dmitryserbin** [comment]
Released 3.1.1890

**Pull request merged**
